# Generated by Django 5.2.1 on 2025-06-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('parent', 'Parent'), ('learner', 'Learner')], default='parent', help_text='Select whether you are a parent or learner', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(help_text='Enter your full name', max_length=150),
        ),
    ]
