# Generated by Django 5.2.1 on 2025-06-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_user_type_alter_customuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('parent', 'Parent'), ('learner', 'Learner')], default='parent', help_text='Select whether you are a parent or learner', max_length=10),
        ),
    ]
